#1. cd
alias cdd="cd ~/Dropbox/Programming/"
alias cv="cd .."
alias cvv="cd ../.."
alias cvvv="cd ../../.."
alias drop="cd ~/Dropbox"
alias dl="cd ~/Downloads"
alias org="cd ~/Dropbox/Org"
alias guitar="cd ~/Dropbox/Guitar/Guitar-Video"

#2. Builtin Tools
alias ll="ls -alhFG"
alias la="ls -aG"
alias ff="open ."
alias tt="type"
alias rm="rm -i"
alias bash="bash -l"
alias -g ggg="| grep  --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}"
alias -g gg="| rg"
alias copy="pbcopy"
alias dus="du -sh"

#3. installed tools alias
alias pa="realpath"
alias x="emacs -nw"
alias xs="emacs &"
alias spacemacs="HOME=~/.spacemacs /Applications/Emacs.app/Contents/MacOS/Emacs"
alias purcellemacs="HOME=~/.purcellemacs /Applications/Emacs.app/Contents/MacOS/Emacs"
alias preludeemacs="HOME=~/.preludeemacs /Applications/Emacs.app/Contents/MacOS/Emacs"
alias v="mvim -v"
alias vs="mvim"
alias py="$HOME/anaconda3/bin/python"
alias py2="$HOME/anaconda3/envs/python2/bin/python"
alias pip2="$HOME/anaconda3/envs/python2/bin/pip"
alias catt="highlight -O ansi --force"
alias sbt="TERM=xterm-color sbt"
alias tip="cat ~/.useful_bash_commands"
alias screenfetch="screenfetch -E" # -E to ignore error
alias we="weather -u si"
alias zl="z -l"
alias cfg="yadm"
alias timer="utimer -c"
alias stopwatch="utimer -s"
alias sw="utimer -s"

#4. proxy
alias proxyss="export http_proxy=http://127.0.0.1:1087 https_proxy=http://127.0.0.1:1087"
alias proxypanda="export http_proxy=http://127.0.0.1:10080 https_proxy=http://127.0.0.1:10080"
alias unproxy="unset http_proxy https_proxy"
