#1. cd
alias cdd="cd ~/Dropbox/Programming/"
alias cv="cd .."
alias cvv="cd ../.."
alias cvvv="cd ../../.."
alias drop="cd ~/Dropbox"
alias dl="cd ~/Downloads"
alias org="cd ~/Dropbox/Org"
alias guitar="cd ~/Dropbox/Guitar/Guitar-Video"

#2. Builtin Tools
alias ll="ls -alhFG"
alias la="ls -aG"
alias ff="open ."
alias tt="type"
alias rm="rm -i"
alias bash="bash -l"
alias -g gg="| grep  --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}"
alias copy="pbcopy"
alias dus="du -sh"

#c installed tools alias
alias pa="realpath"
alias x="/Applications/Emacs.app/Contents/MacOS/Emacs -nw"
alias xs="/Applications/Emacs.app/Contents/MacOS/Emacs"
alias spacemacs="HOME=~/.spacemacs /Applications/Emacs.app/Contents/MacOS/Emacs"
alias purcellemacs="HOME=~/.purcellemacs /Applications/Emacs.app/Contents/MacOS/Emacs"
alias preludeemacs="HOME=~/.preludeemacs /Applications/Emacs.app/Contents/MacOS/Emacs"
alias v="/usr/local/bin/mvim -v"
alias vs="/usr/local/bin/mvim"
alias py="$HOME/anaconda/bin/python"
alias py2="$HOME/anaconda/envs/ipykernel_py2/bin/python"
alias pip2="$HOME/anaconda/envs/ipykernel_py2/bin/pip"
alias activatezwei="source activate ipykernel_py2"
alias activatedrei="source activate base"
alias catt="highlight -O ansi --force"
alias sbt="TERM=xterm-color sbt"
alias tip="cat ~/.useful_bash_commands"
alias screenfetch="screenfetch -E" # -E to ignore error
alias we="weather -u si"
alias zl="z -l"
alias cfg="yadm"
