#!/bin/bash

apps=(
  "Emacs"
  #  "iTerm" #  Don't replace it, since its new icon looks good
)

for app in "${apps[@]}"; do
  new_icon="${DROPBOX}/App Icons/${app}.icns"
  app_dir="/Applications/${app}.app"
  if [[ -f "${new_icon}" ]] && [[ -d "${app_dir}" ]]; then
    cp "${new_icon}" "${app_dir}/Contents/Resources/${app}.icns"
    touch "${app_dir}"
    echo "Finished changing icon: ${app}"
  else
    echo "Icon files does not exist or ${app} is not installed"
  fi
done
